version: '3'
services:
  # Redis
  redis:
    image: redis:latest
    container_name: my-redis
    ports:
      - "6379:6379"
    networks:
      - my_network

  #Spring boot application
  spring-app:
    image: my-project
    container_name: my-spring-app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    networks:
      - my_network

networks:
  my_network: